name: Java CI with Maven

on:
  push:
    branches: [ "main", "desenvolvimento" ]
  pull_request:
    branches: [ "main", "desenvolvimento" ]

jobs:
  checkout_code:
    runs-on: ubuntu-latest

    outputs:
      timestamp: ${{ steps.set_output.outputs.timestamp }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set output
        id: set_output
        run: echo "::set-output name=timestamp::$(date +%s)"

  build:
    needs: checkout_code
    runs-on: ubuntu-latest

    steps:


      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build project
        run: mvn clean install -DskipTests
